name: picture_cropper
description: Flutter package for capturing and cropping photos from camera or gallery.
version: 0.1.4
repository: https://github.com/jhk-im/picture_cropper
maintainers:
  - jayhk.dev@gmail.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  flutter_blurhash: ^0.8.2
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
